### ISSUE TITLE
error: {"code":-1,"message":"PoW mining not allowed"}

### ISSUE THREAD

**Issue by GenTarkin** [mammix2/boostcoin-core#2]
I thought this coin was PoW mineable right now, according to a blockchain explorer there are PoW blocks ... but when I download the source, compile and wait til blockchain is downloading ... I get the message returned above on "./boostcoind getwork"
config file:
rpcuser=user
rpcpassword=pass
rpcallowip=127.0.0.1
server=1
listen=1
gen=0
staking=0
rpcport=9698
port=9697

**Comment by mammix2** [comment]
you need to add this switch to the .conf file
powenable=1

**Comment by GenTarkin** [comment]
Thanks a bunch! works now =)
