### ISSUE TITLE
boostcoin daemon rejecting pool found blocks

### ISSUE THREAD

**Issue by GenTarkin** [mammix2/boostcoin-core#3]
Im trying to use nomp / unomp and mining for boostcoin.
nomp / unomp accepts shares from x13 miners but when a block is found and submitted to the boostcoin daemon the following error is in daemon's debug.log file:
ThreadRPCServer method=submitblock
ERROR: CheckBlock() : first tx is not coinbase
ERROR: ProcessBlock() : CheckBlock FAILED

Is there some nonstandard block data that the pool doesnt know how to submit?? I dont know whats causing the problem =/

**Comment by mammix2** [comment]
Boostcoin uses a slightly different block output which consists of 2x TX. The mined output and the foundation fee TX which is formatted here.
https://github.com/mammix2/boostcoin-core/blob/master/src/rpcmining.cpp#L557

Im not very clued up with unomp or m-pos pool setup, and TBH its been so long since PoW mining was first available on the project im not really sure how the mining pools adjusted for the extra specification to standard PoW.

**Comment by GenTarkin** [comment]
I saw that and suspected as much, do you know where that payout address/pubkey and amount of the foundation tx is stored at in source code?

**Comment by CryptoCanary** [comment]
I had to add this to EGC, a Boostcoin descendant, at the request of a pool OP: https://github.com/EverGreenCoinDev/EverGreenCoin/commit/1f53769feca6797b9090aba3a821288cb66ceec0#diff-c2c990fee1c3381462640e80ae7db0d0   I am not sure if it is applicable or answers your question, but figured it may.

**Comment by GenTarkin** [comment]
you had to add that to the coins source code yes?

Also, was this for a nomp/unomp pool?, if so do you recall any of the coin/poolconfigs specific to the coin?

Update, I added those lines to source and recompiled. Now getblocktemplate shows payee addy and an amount. Pool still returns same error =/  ...
I noticed in EGC these lines are commented out:
   // result.push_back(Pair("charityvalue", (int64_t)pblock->vtx[0].vout[0].nValue));  // EGC un
   // result.push_back(Pair("target", hashTarget.GetHex())); // EGC un

Should I do the same for boostcoin source? ...

**Comment by mammix2** [comment]
the charityvalue output is needed in boostcoin during the PoW period so cant be commented out until the PoW phase is complete after block 1140000

The foundation / charity output TX pubkey is here
https://github.com/mammix2/boostcoin-core/blob/master/src/main.h#L44

**Comment by GenTarkin** [comment]
So, I wonder if I just tell the pool software to point something over 1.3 to the address shown above in the coinbase tx... will that work? (in addition to the normal reward going back to the wallet of course)

UPDATE: I guess it doesnt work =( I set a rewardrecipient to the donation address and 1.29% of block reward ... no dice.

**Comment by GenTarkin** [comment]
I solved the problem woohoo! It took 3 changes overall:
1. @CryptoCanary thanks so much for this hint, this was step one in exposing those values via "getblocktemplate"
2. Fixing nomp source code ... the code they put in to deal w/ "masternodes" for darkcoin I believe .. ended up miscalculating the payee & payee_amount values for every other coin(where required). So I restored those calculations to their more raw format as used by other coins.
3. After cross referencing several otherpool software packages , I had to put "Reward": "POS" in the coins config file.

Now NOMP is submitting valid blocks to the daemon woohoo!!!

**Comment by mammix2** [comment]
@GenTarkin, before i close the issue, can you explain a little more about the changes you made to NOMP?
it would be helpful to others who want to set up the same X13 pools.
Thanks

**Comment by GenTarkin** [comment]
1. Make the changes to coin daemon source code as @CryptoCanary outlined here:
https://github.com/EverGreenCoinDev/EverGreenCoin/commit/1f53769feca6797b9090aba3a821288cb66ceec0#diff-c2c990fee1c3381462640e80ae7db0d0

2. In NOMP source, change https://github.com/zone117x/node-stratum-pool/blob/master/lib/transactions.js#L136 to: 
         var payeeReward = rpcData.payee_amount;

3. In NOMP coins/coin.json ensure theres entry: 
"Reward": "POS"

**Comment by mammix2** [comment]
@GenTarkin nice one, thanks for the info.

**Comment by mammix2** [comment]
also i forgot to ask, is your pool available to the public to use? If it is can you post in the forum and Slack with the details. Thanks

**Comment by GenTarkin** [comment]
@mammix2 its a private pool =)

**Comment by mammix2** [comment]
ok cool, thanks for posting the changes anyway :)
